baseURL = 'https://cameronyule.com/'
languageCode = 'en-gb'
title = "Cameron Yule's blog"
theme = 'nostyleplease'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  sectionPagesMenu = "main"
