baseURL = 'https://cameronyule.com/'
languageCode = 'en-gb'
title = "Cameron Yule"
theme = 'nostyleplease'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  sectionPagesMenu = "main"

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  bookmarks = "/:year/:month/:day/:slug/"
  til = "/:year/:month/:day/:slug/"
