baseURL = 'https://cameronyule.com/'
languageCode = 'en-gb'
title = "Cameron Yule's blog"
theme = 'nostyleplease'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  sectionPagesMenu = "main"

[permalinks]
  bookmarks = "/bookmarks/:year/:month/:day/:slug/"
  notes = "/notes/:year/:month/:day/:slug/"
  til = "/til/:year/:month/:day/:slug/"
